### ISSUE TITLE
Major refactoring

### ISSUE THREAD

**Issue by iafisher** [HCDigitalScholarship/ticha-magic#10]
Problem: There are too many scripts and Python files and it's hard to understand and change.

Proposed solution:
- One script for each printed text (Cordova's Arte, Levanto's Arte, Levanto's Catechismo) that generates all the necessary output (original HTML, regularized  HTML, outline)
- Less generality. Part of the reason this repo is so overgrown is because I tried to make it more general than it needs to be. In the past four years we've only needed to work with three printed texts: it's okay to specialize the code to work with these particular texts.
- You could have this output wrapped in a tarball or zip archive for even greater simplicity, but you'd also have to modify the server to accept it instead of three separate files
- More tests!

@cstuartroe and @ellin2 : I'm going to start working on this, but it's likely I won't finish before I graduate, so be prepared to take over when I'm gone. :coffin:

**Comment by iafisher** [comment]
This work will take place on the refactor branch.

**Comment by cstuartroe** [comment]
These are good thoughts, but I think it'd be a good call to check with Brook before we make the repo less general - whether it makes sense has a lot to do with her anticipation of getting other large texts. The next two things on my docket - looking at parsing FLEx dictionary exports and fixing normalization - both bear directly on this repo, so maybe it's a good idea if I stay involved with the work you're doing on this.

**Comment by iafisher** [comment]
I've actually been able to refactor it without sacrificing too much generality at all. I'll do a bit more work on Wednesday and hopefully put in a PR so you guys can review my code.

**Comment by qubist** [comment]
Looks like a lot of the important work mentioned here happened in 43c4040a918e2147fb2e523266adeafad1dfef3a. Closing this
