### ISSUE TITLE
Make outline doesn't work

### ISSUE THREAD

**Issue by iafisher** [HCDigitalScholarship/ticha-magic#9]

**Comment by iafisher** [comment]
Doesn't seem to work (well) with Cordova's Arte either

**Comment by qubist** [comment]
Doesn't work with any text. It consistently outputs an empty document:

```html
<div class="index"><ul /></div>
```

**Comment by qubist** [comment]
Fixed by various changes to this repo and content in `ticha-xml-tei`. See 28b5f79fe5c0599b53964b87387f75eff57172d8 and nearby commits
